fixed several tcl path issues with xm

diff --git a/src/xm/bin/xm b/src/xm/bin/xm
--- a/src/xm/bin/xm
+++ b/src/xm/bin/xm
@@ -23,8 +23,8 @@
 
 [[ -z ${SEQ_MAESTRO_DOMAIN} ]] && echo "SEQ_MAESTRO_DOMAIN not set, maestro installation incomplete" && exit 1 
 
-if ! [[ -f ${SEQ_TCL_BIN}/bin/maestro_wish8.5 ]] ; then 
-    echo "Installation incomplete. tcl/tk bin not found." 
+if ! [[ -f ${SEQ_TCL_BIN}/maestro_wish8.5 ]] ; then 
+    echo "Installation incomplete. tcl/tk bin not found. SEQ_TCL_BIN='${SEQ_TCL_BIN}'" 
     exit 1 
 fi 
 
